name: Ifilo Automation

on:
  schedule:
    - cron: '0 9 * * *'  # اجرای روزانه در ساعت ۹ صبح به وقت UTC
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    env:
      IFILO_USER: ${{ secrets.IFILO_USER }}
      IFILO_PASS: ${{ secrets.IFILO_PASS }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      MAX_VIDEOS: ${{ secrets.MAX_VIDEOS }}

    steps:
      - name: دریافت کد منبع
        uses: actions/checkout@v3

      - name: تنظیم محیط پایتون
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: نصب وابستگی‌ها
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: اجرای downloader.py
        run: |
          echo "شروع اجرای downloader.py"
          python downloader.py
        continue-on-error: true

      - name: بررسی وجود فایل‌های ویدیو
        run: |
          echo "فایل‌های موجود در پوشه فعلی:"
          ls -lah

      - name: اجرای uploader.py
        run: |
          echo "شروع اجرای uploader.py"
          python uploader.py
        continue-on-error: true
