name: Ifilo Trend Uploader

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  upload-trends:
    runs-on: ubuntu-latest
    env:
      IFILO_USER: ${{ secrets.IFILO_USER }}
      IFILO_PASS: ${{ secrets.IFILO_PASS }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      MAX_VIDEOS: ${{ secrets.MAX_VIDEOS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run automation script
        run: python main.py
