name: Ifilo Trend Uploader

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install selenium
      - run: |
          echo "IFILO_USER=${{ secrets.IFILO_USER }}" >> $GITHUB_ENV
          echo "IFILO_PASS=${{ secrets.IFILO_PASS }}" >> $GITHUB_ENV
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> $GITHUB_ENV
          echo "MAX_VIDEOS=${{ secrets.MAX_VIDEOS }}" >> $GITHUB_ENV
          python downloader.py
          python uploader.py
      - uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs/
